# Generated by Django 3.1.5 on 2021-01-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='transaction_count',
            new_name='transactionCount',
        ),
    ]
