# Generated by Django 3.1.5 on 2021-01-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20210116_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='height',
            new_name='heigth',
        ),
    ]
