# Generated by Django 3.1.5 on 2021-01-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_auto_20210116_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='heigth',
            new_name='height',
        ),
    ]
