# Generated by Django 3.1.5 on 2021-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_auto_20210116_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(editable=False),
        ),
    ]
