# Generated by Django 3.1.5 on 2021-01-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_auto_20210116_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-height']},
        ),
    ]
