# Generated by Django 3.1.5 on 2021-01-16 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_auto_20210116_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
